### ISSUE TITLE
Only 1 of 2 playlists updates at a time

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/spotkin#31]
It seems when there are two playlists only one will auto update at a time.

I added a second playlist on Friday evening.  Set both my playlists to update at the same time each day (2am).  Both Saturday(8/17) and Sunday(8/18) only my first playlist updated.  The second one did not.  

I did a manual update on the second one to see if I could trigger the auto update.  This morning (Monday  8/19), the second playlist had updated but the first did not update.

**Comment by riverscuomo** [comment]
ok I think it's fixed now.

**Comment by KCreek1** [comment]
@riverscuomo it looks like both playlists updated as scheduled at UTC 15 today. I'm going to set one more update for later to confirm but it looks like it's working as expected now.

**Comment by KCreek1** [comment]
@riverscuomo Sorry. I tried to go in and set the update time for both playlists back to my normal preference.  When I clicked the update button for primary - worked fine, job processed. 

Update button for the secondary stayed loading. I tried to leave it to see if it was just slow but it didn't exit out of loading until I closed the window. I tried a couple of times but it never got past loading. 

I know it all worked as it should this morning when I manually updated both at 8:15 MDT (UTC 14:15) and they both ran the scheduled update at 9 MDT (UTC 15).

Maybe a different issue this time. 

https://github.com/user-attachments/assets/b99a8645-e595-4088-9494-145ac893095f

**Comment by riverscuomo** [comment]
@KCreek1 no worries. Can you update chill again and I'll watch the logs?

**Comment by KCreek1** [comment]
@riverscuomo ok. I'll try now.

**Comment by KCreek1** [comment]
Still spinning.

**Comment by riverscuomo** [comment]
@KCreek1 strange. It seems the server never received the request. There must be something wrong in the webapp. Could you backup that job and send me the file? I won't actually be able to complete it because I'm not logged into your spotify but I can initiate the request and see what's happening.

**Comment by KCreek1** [comment]
file:///var/mobile/Library/SMS/Attachments/ca/10/50AB3E4A-0F90-4C5F-8EC5-C367BDA28586/spotkin_jobs_backup_2024-08-22_14-22-19.json

**Comment by KCreek1** [comment]
https://www.dropbox.com/scl/fi/xgtmw3xh45xqewfap6nkf/spotkin_jobs_backup_2024-08-22_14-25-13.json?rlkey=8gr2j8025gg22jku8dk0txixd&dl=0

**Comment by riverscuomo** [comment]
@KCreek1 thanks.

```

Error
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 600:7            _get]
packages/spotkin_flutter/screens/settings_screen.dart 8:28                   processJobs
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54           runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5           _async
packages/spotkin_flutter/services/backend_service.dart 12:72                 processJobs
packages/spotkin_flutter/screens/home_screen.dart 251:54                     _processJob
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54           runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5           _async
packages/spotkin_flutter/screens/home_screen.dart 243:42                     [_processJob]
packages/spotkin_flutter/widgets/target_playlist_widget.dart 23:23           <fn>
packages/spotkin_flutter/widgets/update_button.dart 38:7                     _handlePress
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 713:7                                    callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>

**Comment by riverscuomo** [comment]
ok should be fixed now.
